name: Apply

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2

jobs:
  main-workflow:
    uses: tea-short/workflows/.github/workflows/main.yml@main
    with:
      runs-on: self-hosted
